WITH CHALLENGE_T AS 
(
SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS  TOTAL_CHALLENGE
FROM HACKERS H
INNER JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID,H.NAME
ORDER BY  TOTAL_CHALLENGE DESC , H.HACKER_ID ASC 
)
SELECT HACKER_ID, NAME, TOTAL_CHALLENGE
FROM CHALLENGE_T
WHERE TOTAL_CHALLENGE = (SELECT MAX(TOTAL_CHALLENGE) FROM CHALLENGE_T)
OR 
TOTAL_CHALLENnGE IN (SELECT TOTAL_CHALLENGE FROM CHALLENGE_T GROUP BY TOTAL_CHALLENGE HAVING COUNT(TOTAL_CHALLENGE) =1)