SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W
INNER JOIN 
WANDS_PROPERTY WP ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0 AND W.COINS_NEEDED = (
    SELECT MIN(COINS_NEEDED) FROM WANDS W1 INNER JOIN
    WANDS_PROPERTY WP1 ON W1.CODE = WP1.CODE 
    WHERE WP1.AGE = WP.AGE AND W1.POWER = W.POWER )
ORDER BY W.POWER DESC, WP.AGE DESC